version: '2'
services:
    flair-pgsql:
        container_name: "development-postgres-backend"
        image: flairbi/postgres:dev
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=fbiengine
        ports:
        - 5432:5432

    flair-notifications-pgsql:
        image: postgres:9.4-alpine
        container_name: flair-notifications-pgsql
        hostname: flair-notifications-pgsql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=nodeDB
        ports:
            - 5777:5432

    flair-couchdb:
        image: flairbi/couchdb:latest
        container_name: development-couchdb
        restart: always
        labels:
            purpose: View store
            environment: development
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password
        ports:
        - 5984:5984

    flair-registry:
        container_name: flair-registry
        hostname: flair-registry
        labels:
            purpose: Flair config server and service discovery
            environment: development
            traefik.frontend.rule: "PathPrefixStrip: /config"
            traefik.enable: "true"
            traefik.backend: flair-registry
            traefik.port: "8761"
        image: flairbi/flair-registry:v6.0.0
        ports:
        - 8761:8761
        - 8762:8762
        environment:
        - JHIPSTER_SLEEP=0
        - SPRING_PROFILES_ACTIVE=prod
        - BITBUCKET_URI=https://github.com/viz-centric/flair-config.git

    flair-engine-grpc:
        image: flairbi/flair-engine:v2.0.0
        hostname: flair-engine-grpc
        container_name: flair-engine-grpc
        labels:
            purpose: Bankend engine for data calls
            environment: development
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=60
            - SPRING_PROFILES_ACTIVE=oss,grpc
            - POSTGRES_URI=flair-pgsql:5432
            - GRPC_SSL_ENABLED=false
        ports:
        - 6565:6565

    flair-notifications:
        image: flairbi/flair-notifications:v1.0.0
        hostname: FLAIR-NOTIFICATIONS
        container_name: FLAIR-NOTIFICATIONS
        labels:
            purpose: Flair notifications
            environment: development
        ports:
        - 8090:8090
        - 8091:8091
        volumes:
        - ${PWD}/config/flair-notifications:/flair-config
        environment:
        - APP_CONFIG=/flair-config/application-oss.yml
        - NODE_ENV=production
        - SLEEP_TIME=60
        - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
        - GRPC_SSL_ENABLED=false

    flair-bi:
        image: flairbi/flairbi:v2.0.0
        hostname: flair-bi
        container_name: flair-bi
        labels:
            purpose: Flair front end application
            environment: development
            traefik.frontend.rule: "PathPrefixStrip: /flairbi"
            traefik.enable: "true"
            traefik.backend: flair-bi
            traefik.port: "8002"
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=120
            - SPRING_PROFILES_ACTIVE=oss
            - POSTGRES_URI=flair-pgsql:5432
            - GRPC_SSL_ENABLED=false
        ports:
        - 8002:8002

    flair-cache:
        image: flairbi/flair-cache:v2.0.0
        hostname: flair-cache
        container_name: flair-cache
        labels:
            purpose: Flair cache
            environment: development
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
            - SPRING_PROFILES_ACTIVE=prod
            - JHIPSTER_SLEEP=120
            - GRPC_SSL_ENABLED=false
        ports:
            - 12355:12355

    fakesmtp:
        hostname: fakesmtp
        image: digiplant/fake-smtp
        ports:
            - "25:25"
        volumes:
            - ./email:/var/mail
